### ISSUE TITLE
Plugin Installer: Flatpak and Cmake

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#414] opened 2019-10-30 22:54 UTC
Discussion begun in Squiddio_pi Issues section and moved to the more complex plugin, OcpnDraw_pi for resolution of some issues related to flatpak builds.

Start of Discussion:  https://github.com/mauroc/squiddio_pi/issues/86#issuecomment-548143219

**Comment by leamas** [comment] 2019-10-30 23:15
Ok, I'm listening...

**Comment by leamas** [comment] 2019-11-02 08:50
> I found flatpak/.flatpak-builder in the directory structure. I removed it and issued the ./ci/travis-build-flatpak.sh and it built the plugin

The .flatpak-builder directory is a complete copy of sources, intermediaries, results and what not.  It's so big that it should really be removed completely from the history before  merged to keep the git   repo size sane.  Also, please don't forget to add it to .gitignore.

> This suggests that the docker and flatpak build environments are not quite as 'sandboxed' as you may expect.

http://docs.flatpak.org/en/latest/ has a lot of info as to what expect or not. Have you found it when looking for  info?

> Either there is something wrong with the sandboxing or there needs to be a clean up done of any files generated to ensure they cannot impact a future build.

Flatpak binaries are *run* in a sandbox. That is not to say that the build is. Sources, tools and intermediary result are all available in the host. This  eventually  results in a library linked to resources in the  sandbox,  with limited access to the host.

This puts  restraints to the build process. You could compare it to the mingw toolchain which produces windows binaries on a linux host. There are differences, mingw uses cross--compilers, but the basic scenario has a lot of similarities. 

In the end, that flatpak-builder caches results is a major advantage when you build things locally,  since you many times don't need to rebuild dependencies. It is not a bug, it's a feature! If you don't want to use it, there are command line options to flatpak-builder for that.

**Comment by jongough** [comment] 2019-11-02 19:47
The above is relevant to Squiddio, and all other plugins that are going to attempt this process. It has nothing to do with more complex situations. Once the simple plugin process is working well then I will try this plugin as it is more complex.

**Comment by rgleason** [comment] 2019-11-02 21:04
I've been learning about this process from both of you, and I've got to say, you guys butt heads while showing respect. Bravo. I can understand Jon's frustration with not fully understanding a process that Alec has gotten all grubby with before and now has it working.  Be gentle with each other, this is valuable time.

**Closed** 2019-11-18 19:50 UTC
